version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
      #- "3334:3334"
      - "3334-3434:3334-3434"
    image: tranact/ezcash_api_app:development
    # environment:
    #  - EZCASH_PASSWORD=${EZCASH_PASSWORD}

  web:
    build:
      context: "../ez_cash_web_monitor"
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    image: tranact/ezcash_web_app:development
    depends_on:
      - api
    links:
      - api

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    domainname: "ezcash"
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    image: tranact/ezcash_api_nginx:development
