version: '3.1'

secrets:
  ezcash_username:
    external: true
  ezcash_password:
    external: true

services:
  ezcashapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3002:3000"
      - "3334:3334"
      - "3335:3335"
      - "3336:3336"
      #- "3334-3339:3334-3339"
    #image: tranact/ezcash_api_app:development
    image: tranact/ezcash_api_app:local_docker_development
    command: bash -c "rake tud_socketing:start 3334 | rake tud_socketing:start 3335 | rake tud_socketing:start 3336 | rails db:prepare | bundle exec rails s -p 3000 -b '0.0.0.0'"
    #entrypoint: [ "bash", "-c", "nohup rails tud_socketing:start 3334 > /dev/null 2>&1 &", "nohup rails tud_socketing:start 3335 > /dev/null 2>&1 &"]
    secrets:
      - ezcash_username
      - ezcash_password
    environment:
      #- EZCASH_PASSWORD=${EZCASH_PASSWORD}
      - EZCASH_USERNAME_FILE=/run/secrets/ezcash_username
      - EZCASH_PASSWORD_FILE=/run/secrets/ezcash_password

  #ezcashweb:
  #  build:
  #    context: "../ez_cash_web_monitor"
  #    dockerfile: ./Dockerfile
  #  ports:
  #    - "3003:3001"
  #  #image: tranact/ezcash_web_app:development
  #  image: tranact/ezcash_web_app:local_docker_development
  #  depends_on:
  #    - ezcashapi
  #  links:
  #    - ezcashapi

  ezcashtoken:
    build:
      context: "../ez_token"
      dockerfile: ./Dockerfile
    ports:
      - "3003:3000"
    #image: tranact/ezcash_token_app:development
    image: tranact/ezcash_token_app:local_docker_development
    depends_on:
      - ezcashapi
    links:
      - ezcashapi

  #nginx:
  #  build:
  #    context: .
  #    dockerfile: ./nginx/Dockerfile
  #  domainname: "ezcash"
  #  depends_on:
  #    - ezcashapi
  #  ports:
  #    - 80:80
  #    - 443:443
    #image: tranact/ezcash_api_nginx:development
  #  image: tranact/ezcash_api_nginx:local_docker_development
