version: '3'
services:
  app:
    build:
      context: .
      #dockerfile: ./docker/app/Dockerfile
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    #image: jeremysenn/ezcash_api_app
    image: tranact/ezcash_api_app
    # environment:
    #  - EZCASH_PASSWORD=${EZCASH_PASSWORD}
