
AuthParam.create([
  { param_name: 'arca_retract', description: 'Retract Notes (Arca 2600)', active_flag: 0, dev_id: 0, val1_desc: 'Seconds', val1: 30, clone_flag: 1 }, 
  { param_name: 'card_on_file', description: 'Require card to be on file', active_flag: 0, dev_id: 0, clone_flag: 1 },
  { param_name: 'coin_bins_always_up', description: 'Do not take coin bins out of service', active_flag: 0, dev_id: 0, clone_flag: 1 },
  { param_name: 'denom_thresh', description: 'Do not dispense', active_flag: 0, dev_id: 0, val1_desc: 'Denom', val1: 100, val2_desc: 'unless transaction over', val2: 5000, clone_flag: 1 },
  { param_name: 'exp_rule', description: 'Card Expiration', active_flag: 1, dev_id: 0, val1_desc: 'Days (0=midnight same day)', val1: 1, clone_flag: 1 },
  { param_name: 'force_denom', description: 'Always dispense', active_flag: 0, dev_id: 0, val1_desc: 'Denom', val1: 2, val2_desc: 'at least this many bills', val2: 1, val3_desc: 'if transaction over', val3: 2, clone_flag: 1 },
  { param_name: 'hold_period', description: 'Holding period', active_flag: 0, dev_id: 0, val1_desc: 'Days', val1: 0, clone_flag: 1 },
  { param_name: 'max_disp', description: 'Max transaction value', active_flag: 0, dev_id: 0, val1_desc: 'Dollars', val1: 10000, clone_flag: 1 },
  { param_name: 'max_short', description: 'Maximum underdispense', active_flag: 0, dev_id: 0, val1_desc: 'Dollars', val1: 0, clone_flag: 1 },
  { param_name: 'nomultibundle', description: 'Do not allow multi-bundle transactions', active_flag: 1, dev_id: 0, clone_flag: 1 },
  { param_name: 'one_bundle', description: 'Require reswipe after first bundle', active_flag: 0, dev_id: 0, clone_flag: 1 },
  { param_name: 'receipt_always', description: 'Always print receipts', active_flag: 0, dev_id: 0, clone_flag: 1 },
  { param_name: 'retain_on_partial', description: 'Retain card on partial payment', active_flag: 0, dev_id: 0, clone_flag: 1 },
  { param_name: 'unique_receipt', description: 'Require unique 6-digit receipt number', active_flag: 0, dev_id: 0, val1_desc: 'Lookback period (days)', val1: 14, clone_flag: 0 },
  { param_name: 'v1_barcodes', description: 'Allow version 1 barcodes', active_flag: 0, dev_id: 0, clone_flag: 0 },
  { param_name: 'cdu_retract_time', description: 'Retract timer for CDUs', active_flag: 0, dev_id: 0, val1_desc: 'Seconds (0=none)', val1: 0, clone_flag: 0 }
])

CardFieldDesc.create!([
  {field_name: "avail_amt", short_desc: "Avail Amt"},
  {field_name: "bank_id_nbr", short_desc: "Bank ID"},
  {field_name: "card_amt", short_desc: "Total Amt"},
  {field_name: "card_nbr", short_desc: "Card Nbr"},
  {field_name: "card_status", short_desc: "Status"},
  {field_name: "dev_id", short_desc: "Dev ID"},
  {field_name: "issued_date", short_desc: "Date Issued"},
  {field_name: "last_activity_date", short_desc: "Last Used"}
])

DevType.create!([
  {DevType: 2, description: "Arca 2600"},
  {DevType: 3, description: "Arca 2000"},
  {DevType: 5, description: "De La Rue"},
  {DevType: 6, description: "Diebold"},
  {DevType: 7, description: "Coin XPress"},
  {DevType: 8, description: "NDC ATM"},
  {DevType: 9, description: "PIN Pad (Kiosk)"},
  {DevType: 10, description: "Equinox PIN Pad (TCP/IP)"},
  {DevType: 11, description: "Fujitsu Dispenser"},
  {DevType: 12, description: "Glory Cash Acceptor"}
])

ErrorDesc.create!([
  {error_code: 0, short_desc: "Success", long_desc: "No errors during processing."},
  {error_code: 65, short_desc: "Invalid BIN", long_desc: "The Bank ID number is invalid. Transact cards should use bin 1111101."},
  {error_code: 92, short_desc: "Timeout", long_desc: "The transaction timed out while waiting for a response from the dispenser."},
  {error_code: 93, short_desc: "Timeout", long_desc: "The transaction timed out while waiting for a response from the coin dispenser."},
  {error_code: 101, short_desc: "Database error", long_desc: "There was an error while trying to access the database. Processing was aborted."},
  {error_code: 112, short_desc: "Nothing remaining on card", long_desc: "If the amount to dispense is decoded as 0, this error will be generated."},
  {error_code: 113, short_desc: "Nothing remaining on card", long_desc: "This card has no remaining balance."},
  {error_code: 114, short_desc: "Invalid card", long_desc: "This card has a bad status (not an active card)."},
  {error_code: 115, short_desc: "Card has already been paid", long_desc: "This card has a status of closed (already paid)."},
  {error_code: 116, short_desc: "Card cancelled", long_desc: "The card has been voided."},
  {error_code: 117, short_desc: "Card not on file.", long_desc: "Card not on file, but require card on file rule in effect."},
  {error_code: 131, short_desc: "PIN verification error.", long_desc: "An incorrect PIN was entered."},
  {error_code: 132, short_desc: "PIN retries exceeded.", long_desc: "An incorrect PIN was entered too many times."},
  {error_code: 135, short_desc: "New PINs do not match.", long_desc: "A PIN change was requested but the confirmation PIN did not match the new PIN."},
  {error_code: 153, short_desc: "Card expired", long_desc: "The date on the card is too old based on the allowed time to use the card. Check the expiration period in the software."},
  {error_code: 154, short_desc: "Card locked", long_desc: "The card is currently being processed."},
  {error_code: 155, short_desc: "In hold period", long_desc: "Attempt to cash a card still in the holding period."},
  {error_code: 316, short_desc: "Invalid date", long_desc: "There was an invalid date encoded onto the card."},
  {error_code: 317, short_desc: "Invalid Track 2/Barcode", long_desc: "This error code indicates that the track 2 or barcode did not decode properly. Possible causes include encoding with the incorrect key, a card read or write error, etc."},
  {error_code: 318, short_desc: "Database error", long_desc: "The database engine reported an error during the transaction."},
  {error_code: 319, short_desc: "Unknown Transaction", long_desc: "An unknown supervisor transaction was detected."},
  {error_code: 602, short_desc: "Unable to dispense with available currency", long_desc: "Amount requested could not be dispensed using available currencies. Check to ensure that cassettes have necessary denominations."},
  {error_code: 603, short_desc: "Amount exceeds maximum", long_desc: "Amount requested exceeds the maximum amount specified in the settings."},
  {error_code: 604, short_desc: "Partial Dispense.  Please scan ticket again.", long_desc: "Some but not all of the amount requested was dispensed before the allowed number of retries was exceeded. Most likely, the dispenser is out of one or more currencies."},
  {error_code: 605, short_desc: "Bills Retracted", long_desc: "Some or all of the notes presented were not taken in the allowed time and were retracted. There is no way to know if some or all of the notes were retracted without balancing the machine or checking the reject bin."},
  {error_code: 606, short_desc: "Partial Dispense", long_desc: "Could not pay the entire amount in one bundle. Requires the card to be re-inserted or barcode to be rescanned to pay remaining amount.'"},
  {error_code: 607, short_desc: "Amount exceeds one bundle", long_desc: "Amount requested could not be dispensed in one bundle, and the settings do not allow multiple bundles to be dispensed.614No dispenseNo cash was dispensed before the allowed number of retries was exceeded. There could be a jam in the dispenser, or one or more cassettes could be out of bills."},
  {error_code: 608, short_desc: "Transaction took too long", long_desc: "The dispenser could not dispense in a reasonable time, usually one minute."},
  {error_code: 609, short_desc: "Partial Coin Dispense", long_desc: "Coin changer did not pay entire amount of change due."},
  {error_code: 610, short_desc: "Coin dispenser not available", long_desc: "Coin changer is disconnected or not in service."},
  {error_code: 611, short_desc: "Amount exceeds one bundle. Please reswipe.", long_desc: "Amount requested could not be dispensed in one bundle. Reswipe required to dispense remaining amount."},
  {error_code: 614, short_desc: "No dispense SCAN TICKET AGAIN", long_desc: "No cash was dispensed before the allowed number of retries was exceeded. There could be a jam in the dispenser, or one or more cassettes could be out of bills."},
  {error_code: 615, short_desc: "Coin changer busy", long_desc: "Could not process the transaction while the coin changer was busy with the previous transaction."},
  {error_code: 701, short_desc: "Could not get signature.", long_desc: "There was an error while attempting to get the signature."},
  {error_code: 702, short_desc: "Received command reject.", long_desc: "Command reject was received in response to dispense request; bills dispensed unknown."},
  {error_code: 800, short_desc: "Authorizer not found.", long_desc: "There was an unknown authorizer specified in the database."},
  {error_code: 801, short_desc: "Unknown opcode.", long_desc: "There was no matching opcode specified in the database."},
  {error_code: 802, short_desc: "No Heavy Metal account.", long_desc: "Cannot process transaction block due to missing Heavy Metal Account."},
  {error_code: 803, short_desc: "No Vendor account.", long_desc: "Cannot process transaction block due to missing Vendor Account."},
  {error_code: 804, short_desc: "Block could not be funded.", long_desc: "One or more block funding transactions did not clear."},
  {error_code: 805, short_desc: "Authorizer offline.", long_desc: "Could not send message to Authorizer."},
  {error_code: 900, short_desc: "Invalid Tran Code", long_desc: "Unable to authorize transaction due to invalid tran codes."},
  {error_code: 901, short_desc: "Invalid From Acct", long_desc: "Unable to authorize transaction (\"From\" account not found)."},
  {error_code: 902, short_desc: "Invalid To Acct", long_desc: "Unable to authorize transaction (\"To\" account not found)."},
  {error_code: 903, short_desc: "From Acct inactive", long_desc: "Unable to authorize transaction (\"From\" account inactive)."},
  {error_code: 904, short_desc: "To Acct inactive", long_desc: "Unable to authorize transaction (\"To\" account inactive)."},
  {error_code: 905, short_desc: "Insufficient funds", long_desc: "Insufficient funds in \"from\" account."},
  {error_code: 999, short_desc: "Unexpected system error", long_desc: "There was an unexpected exception during processing."},
  {error_code: 1001, short_desc: "Customer ID not found.", long_desc: "The user was not found in the user_profiles table."},
  {error_code: 1002, short_desc: "PIN entries do not match.", long_desc: "The reentered PIN does not match the original entry."},
  {error_code: 1003, short_desc: "Device inactive.", long_desc: "Cannot process a transaction from an inactive device."},
  {error_code: 1004, short_desc: "User Cancelled.", long_desc: "User pressed the Cancel button."},
  {error_code: 1005, short_desc: "Unable to reverse", long_desc: "Unable to reverse transaction due to original transaction not found."},
  {error_code: 1006, short_desc: "Unable to reverse", long_desc: "Cannot reverse; specified receipt number=0."}
])

RoleDescription.create!([
  {RoleID: 0, RoleDescription: "Unused"},
  {RoleID: 1, RoleDescription: "User"},
  {RoleID: 2, RoleDescription: "Cashier"},
  {RoleID: 3, RoleDescription: "Device Manager"},
  {RoleID: 4, RoleDescription: "Replenisher"},
  {RoleID: 5, RoleDescription: "Administrator"},
  {RoleID: 6, RoleDescription: "Cash Replenisher"},
  {RoleID: 7, RoleDescription: "Coin Replenisher"}
])

RolePermission.create!([
  {RoleID: 1, PermissionID: 0, Enabled: 1},
  {RoleID: 1, PermissionID: 1, Enabled: 1},
  {RoleID: 2, PermissionID: 0, Enabled: 1},
  {RoleID: 2, PermissionID: 1, Enabled: 1},
  {RoleID: 2, PermissionID: 9, Enabled: 1},
  {RoleID: 3, PermissionID: 0, Enabled: 1},
  {RoleID: 3, PermissionID: 1, Enabled: 1},
  {RoleID: 3, PermissionID: 4, Enabled: 1},
  {RoleID: 3, PermissionID: 5, Enabled: 1},
  {RoleID: 3, PermissionID: 9, Enabled: 1},
  {RoleID: 3, PermissionID: 10, Enabled: 1},
  {RoleID: 4, PermissionID: 0, Enabled: 1},
  {RoleID: 4, PermissionID: 1, Enabled: 1},
  {RoleID: 4, PermissionID: 7, Enabled: 1},
  {RoleID: 4, PermissionID: 8, Enabled: 1},
  {RoleID: 5, PermissionID: 0, Enabled: 1},
  {RoleID: 5, PermissionID: 1, Enabled: 1},
  {RoleID: 5, PermissionID: 2, Enabled: 1},
  {RoleID: 5, PermissionID: 3, Enabled: 1},
  {RoleID: 5, PermissionID: 4, Enabled: 1},
  {RoleID: 5, PermissionID: 5, Enabled: 1},
  {RoleID: 5, PermissionID: 6, Enabled: 1},
  {RoleID: 5, PermissionID: 7, Enabled: 1},
  {RoleID: 5, PermissionID: 8, Enabled: 1},
  {RoleID: 5, PermissionID: 9, Enabled: 1},
  {RoleID: 5, PermissionID: 10, Enabled: 1},
  {RoleID: 5, PermissionID: 11, Enabled: 1},
  {RoleID: 6, PermissionID: 0, Enabled: 1},
  {RoleID: 6, PermissionID: 1, Enabled: 1},
  {RoleID: 6, PermissionID: 7, Enabled: 1},
  {RoleID: 7, PermissionID: 0, Enabled: 1},
  {RoleID: 7, PermissionID: 1, Enabled: 1},
  {RoleID: 7, PermissionID: 8, Enabled: 1}
])

StatusDesc.create!([
  {status: "0006", short_desc: "Magnets set incorrectly.", caution_flag: 1, alert_flag: 0},
  {status: "000K", short_desc: "Out of notes, unknown cassette.", caution_flag: 1, alert_flag: 0},
  {status: "000N", short_desc: "Double detect (notes rejected).", caution_flag: 1, alert_flag: 0},
  {status: "0012", short_desc: "Cassette 1 low on notes.", caution_flag: 0, alert_flag: 0},
  {status: "0013", short_desc: "Cassette 1 out of notes.", caution_flag: 1, alert_flag: 1},
  {status: "0016", short_desc: "Cassette 2 out of notes.", caution_flag: 1, alert_flag: 1},
  {status: "0018", short_desc: "Cassette 2 low on notes.", caution_flag: 0, alert_flag: 0},
  {status: "0019", short_desc: "Cassette 3 out of notes.", caution_flag: 1, alert_flag: 1},
  {status: "0024", short_desc: "Cassette 3 low on notes.", caution_flag: 0, alert_flag: 0},
  {status: "0025", short_desc: "Cassette 4 out of notes.", caution_flag: 1, alert_flag: 1},
  {status: "0030", short_desc: "Cassette 4 low on notes.", caution_flag: 0, alert_flag: 0},
  {status: "0101", short_desc: "Pick failure.", caution_flag: 1, alert_flag: 0},
  {status: "0210", short_desc: "Cash Handler routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "0211", short_desc: "Cassette 1 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "0212", short_desc: "Cassette 2 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "0213", short_desc: "Cassette 3 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "0214", short_desc: "Cassette 4 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "0220", short_desc: "Cash Handler Warning condition, investigate.", caution_flag: 0, alert_flag: 0},
  {status: "0221", short_desc: "Cassette 1 Warning condition, investigate.", caution_flag: 0, alert_flag: 0},
  {status: "0222", short_desc: "Cassette 2 Warning condition, investigate.", caution_flag: 0, alert_flag: 0},
  {status: "0223", short_desc: "Cassette 3 Warning condition, investigate.", caution_flag: 0, alert_flag: 0},
  {status: "0224", short_desc: "Cassette 4 Warning condition, investigate.", caution_flag: 0, alert_flag: 0},
  {status: "0230", short_desc: "Cash Handler Suspended due to suspected tampering", caution_flag: 1, alert_flag: 3},
  {status: "0231", short_desc: "Cassette 1 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "0232", short_desc: "Cassette 2 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "0233", short_desc: "Cassette 3 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "0234", short_desc: "Cassette 4 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "0240", short_desc: "Cash handler Fatal error.", caution_flag: 1, alert_flag: 3},
  {status: "0241", short_desc: "Cassette 1 Fatal error.", caution_flag: 1, alert_flag: 1},
  {status: "0242", short_desc: "Cassette 2 Fatal error.", caution_flag: 1, alert_flag: 1},
  {status: "0243", short_desc: "Cassette 3 Fatal error.", caution_flag: 1, alert_flag: 1},
  {status: "0244", short_desc: "Cassette 4 Fatal error.", caution_flag: 1, alert_flag: 1},
  {status: "1001", short_desc: "Unknown unsolicited status message type.", caution_flag: 0, alert_flag: 0},
  {status: "1002", short_desc: "Power interruption.", caution_flag: 0, alert_flag: 0},
  {status: "1003", short_desc: "Card not taken in allowed time, card captured or jammed.", caution_flag: 0, alert_flag: 0},
  {status: "1004", short_desc: "The mechanism failed to eject the card and it was captured or jammed.", caution_flag: 0, alert_flag: 0},
  {status: "1005", short_desc: "Card read error", caution_flag: 0, alert_flag: 0},
  {status: "1006", short_desc: "Error in Track 3 data", caution_flag: 0, alert_flag: 0},
  {status: "1007", short_desc: "Card capture bin overfilled.", caution_flag: 0, alert_flag: 3},
  {status: "1008", short_desc: "Short dispense.", caution_flag: 1, alert_flag: 0},
  {status: "1009", short_desc: "No notes dispensed.", caution_flag: 1, alert_flag: 2},
  {status: "101 ", short_desc: "Pick failure.", caution_flag: 1, alert_flag: 0},
  {status: "1010", short_desc: "Receipt printer failure.", caution_flag: 0, alert_flag: 0},
  {status: "1011", short_desc: "Receipt printer not configured.", caution_flag: 0, alert_flag: 0},
  {status: "1012", short_desc: "Receipt paper low.", caution_flag: 0, alert_flag: 0},
  {status: "1013", short_desc: "Receipt paper out.", caution_flag: 0, alert_flag: 0},
  {status: "1014", short_desc: "Receipt ribbon replacement recommended.", caution_flag: 0, alert_flag: 0},
  {status: "1015", short_desc: "Receipt ribbon replacement mandatory.", caution_flag: 0, alert_flag: 0},
  {status: "1016", short_desc: "Receipt print head replacement recommended.", caution_flag: 0, alert_flag: 0},
  {status: "1017", short_desc: "Receipt print head replacement mandatory.", caution_flag: 0, alert_flag: 0},
  {status: "1018", short_desc: "Receipt Knife replacement recommended.", caution_flag: 0, alert_flag: 0},
  {status: "1020", short_desc: "Journal print operation not completed", caution_flag: 0, alert_flag: 0},
  {status: "1021", short_desc: "Journal printer not configured", caution_flag: 0, alert_flag: 0},
  {status: "1022", short_desc: "Journal printer backup activated", caution_flag: 0, alert_flag: 0},
  {status: "1023", short_desc: "Journal backup and reprint terminated", caution_flag: 0, alert_flag: 0},
  {status: "1024", short_desc: "Journal printer backup reprint started", caution_flag: 0, alert_flag: 0},
  {status: "1025", short_desc: "Journal printer backup halted", caution_flag: 0, alert_flag: 0},
  {status: "1026", short_desc: "Journal printer backup log security error", caution_flag: 0, alert_flag: 0},
  {status: "1027", short_desc: "Journal printer backup reprint halted", caution_flag: 0, alert_flag: 0},
  {status: "1028", short_desc: "Journal printer backup tamper state entered", caution_flag: 0, alert_flag: 0},
  {status: "1032", short_desc: "Journal paper low.", caution_flag: 0, alert_flag: 0},
  {status: "1033", short_desc: "Journal paper out.", caution_flag: 0, alert_flag: 0},
  {status: "1034", short_desc: "Journal ribbon replacement recommended.", caution_flag: 0, alert_flag: 0},
  {status: "1035", short_desc: "Journal ribbon replacement mandatory.", caution_flag: 0, alert_flag: 0},
  {status: "1036", short_desc: "Journal print head replacement recommended.", caution_flag: 0, alert_flag: 0},
  {status: "1037", short_desc: "Journal print head replacement mandatory.", caution_flag: 0, alert_flag: 0},
  {status: "1041", short_desc: "Encryptor error.", caution_flag: 0, alert_flag: 0},
  {status: "1042", short_desc: "Encryptor not configured.", caution_flag: 0, alert_flag: 0},
  {status: "1043", short_desc: "Encryptor tampering detected.", caution_flag: 0, alert_flag: 0},
  {status: "1044", short_desc: "Encryptor keyspace setup is illegal.", caution_flag: 0, alert_flag: 0},
  {status: "1045", short_desc: "Encryptor communications failure.", caution_flag: 0, alert_flag: 0},
  {status: "1050", short_desc: "Supervisor mode exit.", caution_flag: 0, alert_flag: 0},
  {status: "1051", short_desc: "Supervisor mode entry.", caution_flag: 0, alert_flag: 0},
  {status: "1060", short_desc: "In Service Supervisor mode exit.", caution_flag: 0, alert_flag: 0},
  {status: "1061", short_desc: "In Service Supervisor mode entry.", caution_flag: 0, alert_flag: 0},
  {status: "1070", short_desc: "Clear fitness executed.", caution_flag: 0, alert_flag: 0},
  {status: "1071", short_desc: "Faulty dispense, notes dispensed unknown.", caution_flag: 1, alert_flag: 0},
  {status: "1072", short_desc: "Some notes retracted after presentation.", caution_flag: 1, alert_flag: 0},
  {status: "1073", short_desc: "Command reject.", caution_flag: 1, alert_flag: 0},
  {status: "1081", short_desc: "Coin low thresholds not set. No coins dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1083", short_desc: "Invalid hopper requested. No coins dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1084", short_desc: "Coin dispense failed (non-jam). Some coins may have been dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1089", short_desc: "Coin dispense failed (hopper jam). Some coins may have been dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1090", short_desc: "Coin dispense failed (chute jam). Some coins may have been dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1091", short_desc: "Coin dispense failed (chute exit block). No coins dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1092", short_desc: "Coin dispense failed due to CDM fitness. No coins dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1093", short_desc: "Coin dispense failed due to tamper detection. No coins dispensed.", caution_flag: 1, alert_flag: 0},
  {status: "1095", short_desc: "Coin hopper 1 fatal status.", caution_flag: 1, alert_flag: 0},
  {status: "1096", short_desc: "Coin hopper 2 fatal status.", caution_flag: 1, alert_flag: 0},
  {status: "1097", short_desc: "Coin hopper 3 fatal status.", caution_flag: 1, alert_flag: 0},
  {status: "1098", short_desc: "Coin hopper 4 fatal status.", caution_flag: 1, alert_flag: 0},
  {status: "1100", short_desc: "Load Begun.", caution_flag: 0, alert_flag: 0},
  {status: "1101", short_desc: "Load Completed.", caution_flag: 0, alert_flag: 0},
  {status: "1110", short_desc: "Out of service.", caution_flag: 0, alert_flag: 0},
  {status: "1111", short_desc: "In service.", caution_flag: 0, alert_flag: 0},
  {status: "1112", short_desc: "Communcations lost.", caution_flag: 0, alert_flag: 0},
  {status: "1113", short_desc: "Communcations Restored.", caution_flag: 0, alert_flag: 0},
  {status: "1114", short_desc: "Entering bill remix algorithm.", caution_flag: 0, alert_flag: 0},
  {status: "1121", short_desc: "Coin hopper 1 low on coins.", caution_flag: 0, alert_flag: 0},
  {status: "1122", short_desc: "Coin hopper 2 low on coins.", caution_flag: 0, alert_flag: 0},
  {status: "1123", short_desc: "Coin hopper 3 low on coins.", caution_flag: 0, alert_flag: 0},
  {status: "1124", short_desc: "Coin hopper 4 low on coins.", caution_flag: 0, alert_flag: 0},
  {status: "1131", short_desc: "Coin hopper 1 empty.", caution_flag: 1, alert_flag: 0},
  {status: "1132", short_desc: "Coin hopper 2 empty.", caution_flag: 1, alert_flag: 0},
  {status: "1133", short_desc: "Coin hopper 3 empty.", caution_flag: 1, alert_flag: 0},
  {status: "1134", short_desc: "Coin hopper 4 empty.", caution_flag: 1, alert_flag: 0},
  {status: "1140", short_desc: "Coin dispenser marked down (retries exceeded).", caution_flag: 1, alert_flag: 0},
  {status: "1141", short_desc: "Coin dispenser in service.", caution_flag: 0, alert_flag: 0},
  {status: "12  ", short_desc: "Cassette 1 low on notes.", caution_flag: 0, alert_flag: 0},
  {status: "1200", short_desc: "Vibration and/or heat sensor inactive.", caution_flag: 0, alert_flag: 0},
  {status: "1201", short_desc: "Vibration and/or heat sensor active.", caution_flag: 0, alert_flag: 0},
  {status: "1202", short_desc: "Door contact sensor inactive.", caution_flag: 0, alert_flag: 0},
  {status: "1203", short_desc: "Door contact sensor active.", caution_flag: 0, alert_flag: 0},
  {status: "1204", short_desc: "Door signal sensor inactive.", caution_flag: 0, alert_flag: 0},
  {status: "1205", short_desc: "Door signal sensor active.", caution_flag: 0, alert_flag: 0},
  {status: "1206", short_desc: "Electronics enclosure sensor inactive.", caution_flag: 0, alert_flag: 0},
  {status: "1207", short_desc: "Electronics enclosure sensor active.", caution_flag: 0, alert_flag: 0},
  {status: "1208", short_desc: "Deposit bin out.", caution_flag: 0, alert_flag: 0},
  {status: "1209", short_desc: "Deposit bin in.", caution_flag: 0, alert_flag: 0},
  {status: "1210", short_desc: "Card bin out.", caution_flag: 0, alert_flag: 0},
  {status: "1211", short_desc: "Card bin in.", caution_flag: 0, alert_flag: 0},
  {status: "1212", short_desc: "Currency reject bin out.", caution_flag: 0, alert_flag: 0},
  {status: "1213", short_desc: "Currency reject bin in.", caution_flag: 0, alert_flag: 0},
  {status: "1214", short_desc: "Currency cassette in position 1 (top) out.", caution_flag: 0, alert_flag: 0},
  {status: "1215", short_desc: "Currency cassette in position 1 (top) in.", caution_flag: 0, alert_flag: 0},
  {status: "1216", short_desc: "Currency cassette in position 2 out.", caution_flag: 0, alert_flag: 0},
  {status: "1217", short_desc: "Currency cassette in position 2 in.", caution_flag: 0, alert_flag: 0},
  {status: "1218", short_desc: "Currency cassette in position 3 out.", caution_flag: 0, alert_flag: 0},
  {status: "1219", short_desc: "Currency cassette in position 3 in.", caution_flag: 0, alert_flag: 0},
  {status: "1220", short_desc: "Currency cassette in position 4 (bottom) out.", caution_flag: 0, alert_flag: 0},
  {status: "1221", short_desc: "Currency cassette in position 4 (bottom) in.", caution_flag: 0, alert_flag: 0},
  {status: "1222", short_desc: "Coin dispenser out.", caution_flag: 0, alert_flag: 0},
  {status: "1223", short_desc: "Coin dispenser in.", caution_flag: 0, alert_flag: 0},
  {status: "1224", short_desc: "Coin dispenser hopper 1 out.", caution_flag: 0, alert_flag: 0},
  {status: "1225", short_desc: "Coin dispenser hopper 1 in.", caution_flag: 0, alert_flag: 0},
  {status: "1226", short_desc: "Coin dispenser hopper 2 out.", caution_flag: 0, alert_flag: 0},
  {status: "1227", short_desc: "Coin dispenser hopper 2 in.", caution_flag: 0, alert_flag: 0},
  {status: "1228", short_desc: "Coin dispenser hopper 3 out.", caution_flag: 0, alert_flag: 0},
  {status: "1229", short_desc: "Coin dispenser hopper 3 in.", caution_flag: 0, alert_flag: 0},
  {status: "1230", short_desc: "Coin dispenser hopper 4 out.", caution_flag: 0, alert_flag: 0},
  {status: "1231", short_desc: "Coin dispenser hopper 4 in.", caution_flag: 0, alert_flag: 0},
  {status: "1232", short_desc: "DPM pockets open", caution_flag: 0, alert_flag: 0},
  {status: "1233", short_desc: "DPM pockets closed", caution_flag: 0, alert_flag: 0},
  {status: "13  ", short_desc: "Cassette 1 out of notes.", caution_flag: 1, alert_flag: 0},
  {status: "16  ", short_desc: "Cassette 2 out of notes.", caution_flag: 1, alert_flag: 0},
  {status: "18  ", short_desc: "Cassette 2 low on notes.", caution_flag: 1, alert_flag: 0},
  {status: "19  ", short_desc: "Cassette 3 out of notes.", caution_flag: 1, alert_flag: 0},
  {status: "2001", short_desc: "System is not in a state to dispense (recoverable)", caution_flag: 0, alert_flag: 0},
  {status: "2002", short_desc: "Express Delivery Minor Fault (feed failure, miscount, etc.)", caution_flag: 0, alert_flag: 0},
  {status: "2003", short_desc: "Express Delivery Fatal Fault (dispenser down)", caution_flag: 1, alert_flag: 0},
  {status: "2004", short_desc: "Message Data Error", caution_flag: 0, alert_flag: 0},
  {status: "2005", short_desc: "Checksum Error", caution_flag: 0, alert_flag: 0},
  {status: "2006", short_desc: "Terminal Busy (Maintenance mode or door is open)", caution_flag: 0, alert_flag: 0},
  {status: "2007", short_desc: "Checksum Error", caution_flag: 0, alert_flag: 0},
  {status: "2008", short_desc: "Unable to process (money in throat)", caution_flag: 0, alert_flag: 0},
  {status: "2009", short_desc: "Hard Fault Status (unable to dispense)", caution_flag: 1, alert_flag: 0},
  {status: "2010", short_desc: "Invalid password", caution_flag: 0, alert_flag: 0},
  {status: "2011", short_desc: "Five consecutive invalid passwords", caution_flag: 0, alert_flag: 0},
  {status: "2012", short_desc: "Logon required", caution_flag: 0, alert_flag: 0},
  {status: "2013", short_desc: "Maintenance Mode Status", caution_flag: 0, alert_flag: 0},
  {status: "2014", short_desc: "Power-up status", caution_flag: 0, alert_flag: 0},
  {status: "2015", short_desc: "Bad dispense, probable jam", caution_flag: 0, alert_flag: 0},
  {status: "2016", short_desc: "Dispense is not possible", caution_flag: 0, alert_flag: 0},
  {status: "2017", short_desc: "Denomination error, retry possible", caution_flag: 0, alert_flag: 0},
  {status: "2018", short_desc: "Good partial dispense; continuation possible", caution_flag: 0, alert_flag: 0},
  {status: "2019", short_desc: "Presenter door open prior to dispense", caution_flag: 0, alert_flag: 0},
  {status: "2020", short_desc: "Delivery failure (money not presented)", caution_flag: 0, alert_flag: 0},
  {status: "2021", short_desc: "Previous money in stacker, unable to dispense", caution_flag: 0, alert_flag: 0},
  {status: "2022", short_desc: "Delivery failure (money may have been vulnerable)", caution_flag: 0, alert_flag: 0},
  {status: "2023", short_desc: "Sensors not blocked after dispense, failed dispense", caution_flag: 0, alert_flag: 0},
  {status: "2024", short_desc: "Unsolicited bill from cassette position 1", caution_flag: 0, alert_flag: 0},
  {status: "2025", short_desc: "Unsolicited bill from cassette position 2", caution_flag: 0, alert_flag: 0},
  {status: "2026", short_desc: "Unsolicited bill from cassette position 3", caution_flag: 0, alert_flag: 0},
  {status: "2027", short_desc: "Unsolicited bill from cassette position 4", caution_flag: 0, alert_flag: 0},
  {status: "2028", short_desc: "Unsolicited bill from cassette position 5", caution_flag: 0, alert_flag: 0},
  {status: "2029", short_desc: "Unsolicited bill from cassette position 6", caution_flag: 0, alert_flag: 0},
  {status: "2030", short_desc: "Feed failure from cassette position 1", caution_flag: 0, alert_flag: 0},
  {status: "2031", short_desc: "Feed failure from cassette position 2", caution_flag: 0, alert_flag: 0},
  {status: "2032", short_desc: "Feed failure from cassette position 3", caution_flag: 0, alert_flag: 0},
  {status: "2033", short_desc: "Feed failure from cassette position 4", caution_flag: 0, alert_flag: 0},
  {status: "2034", short_desc: "Feed failure from cassette position 5", caution_flag: 0, alert_flag: 0},
  {status: "2035", short_desc: "Feed failure from cassette position 6", caution_flag: 0, alert_flag: 0},
  {status: "2036", short_desc: "Jam between double-detect switch and exit throat", caution_flag: 0, alert_flag: 0},
  {status: "2037", short_desc: "Jam between double-detect switch and divert throat", caution_flag: 0, alert_flag: 0},
  {status: "2038", short_desc: "Denomination error", caution_flag: 0, alert_flag: 0},
  {status: "2039", short_desc: "Unidentified cassette", caution_flag: 0, alert_flag: 0},
  {status: "2040", short_desc: "During dispenses, the diverter will not go to the exit position", caution_flag: 0, alert_flag: 0},
  {status: "2041", short_desc: "Long or short bill dispensed", caution_flag: 0, alert_flag: 0},
  {status: "2042", short_desc: "Coin low", caution_flag: 0, alert_flag: 0},
  {status: "2043", short_desc: "Coin communications error", caution_flag: 0, alert_flag: 0},
  {status: "2044", short_desc: "Coin denomination error", caution_flag: 0, alert_flag: 0},
  {status: "2045", short_desc: "Fatal coin error", caution_flag: 0, alert_flag: 0},
  {status: "2046", short_desc: "Single and exit counted bills are not equal from position 1", caution_flag: 0, alert_flag: 0},
  {status: "2047", short_desc: "Single and exit counted bills are not equal from position 2", caution_flag: 0, alert_flag: 0},
  {status: "2048", short_desc: "Single and exit counted bills are not equal from position 3", caution_flag: 0, alert_flag: 0},
  {status: "2049", short_desc: "Single and exit counted bills are not equal from position 4", caution_flag: 0, alert_flag: 0},
  {status: "2050", short_desc: "Single and exit counted bills are not equal from position 5", caution_flag: 0, alert_flag: 0},
  {status: "2051", short_desc: "Single and exit counted bills are not equal from position 6", caution_flag: 0, alert_flag: 0},
  {status: "2052", short_desc: "Too many bills dispensed", caution_flag: 0, alert_flag: 0},
  {status: "2053", short_desc: "Timing wheel error", caution_flag: 0, alert_flag: 0},
  {status: "2054", short_desc: "Feed, exit or divert sensor blocked", caution_flag: 0, alert_flag: 0},
  {status: "2055", short_desc: "Counting sensors dirty", caution_flag: 0, alert_flag: 0},
  {status: "2056", short_desc: "Dispenser RAM error", caution_flag: 0, alert_flag: 0},
  {status: "2057", short_desc: "Cassettes shuffled", caution_flag: 0, alert_flag: 0},
  {status: "2058", short_desc: "Diverter will not energize", caution_flag: 0, alert_flag: 0},
  {status: "2059", short_desc: "Divert cassette full", caution_flag: 0, alert_flag: 0},
  {status: "2060", short_desc: "Divert cassette not present", caution_flag: 0, alert_flag: 0},
  {status: "2061", short_desc: "Dispense timeout", caution_flag: 0, alert_flag: 0},
  {status: "2062", short_desc: "Communication data invalid", caution_flag: 0, alert_flag: 0},
  {status: "2063", short_desc: "Dispenser shutdown", caution_flag: 0, alert_flag: 0},
  {status: "2064", short_desc: "Unreported problem with feed module 1", caution_flag: 0, alert_flag: 0},
  {status: "2065", short_desc: "Unreported problem with feed module 2", caution_flag: 0, alert_flag: 0},
  {status: "2066", short_desc: "Unreported problem with feed module 3", caution_flag: 0, alert_flag: 0},
  {status: "2067", short_desc: "Unreported problem with feed module 4", caution_flag: 0, alert_flag: 0},
  {status: "2068", short_desc: "Unreported problem with feed module 5", caution_flag: 0, alert_flag: 0},
  {status: "2069", short_desc: "Unreported problem with feed module 6", caution_flag: 0, alert_flag: 0},
  {status: "210 ", short_desc: "Cash Handler routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "211 ", short_desc: "Cassette 1 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "212 ", short_desc: "Cassette 2 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "213 ", short_desc: "Cassette 3 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "214 ", short_desc: "Cassette 4 routine errors.", caution_flag: 0, alert_flag: 0},
  {status: "230 ", short_desc: "Cash Handler Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "231 ", short_desc: "Cassette 1 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "232 ", short_desc: "Cassette 2 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "233 ", short_desc: "Cassette 3 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "234 ", short_desc: "Cassette 4 Suspended due to suspected tampering", caution_flag: 1, alert_flag: 0},
  {status: "24  ", short_desc: "Cassette 3 low on notes.", caution_flag: 0, alert_flag: 0},
  {status: "240 ", short_desc: "Cash handler Fatal error.", caution_flag: 1, alert_flag: 0},
  {status: "241 ", short_desc: "Cassette 1 Fatal error.", caution_flag: 1, alert_flag: 0},
  {status: "242 ", short_desc: "Cassette 2 Fatal error.", caution_flag: 1, alert_flag: 0},
  {status: "243 ", short_desc: "Cassette 3 Fatal error.", caution_flag: 1, alert_flag: 0},
  {status: "244 ", short_desc: "Cassette 4 Fatal error.", caution_flag: 1, alert_flag: 0},
  {status: "25  ", short_desc: "Cassette 4 out of notes.", caution_flag: 1, alert_flag: 0},
  {status: "30  ", short_desc: "Cassette 4 low on notes.", caution_flag: 0, alert_flag: 0},
  {status: "47  ", short_desc: "Transport problem.", caution_flag: 1, alert_flag: 0},
  {status: "49  ", short_desc: "Pick Sensor failure.", caution_flag: 1, alert_flag: 0},
  {status: "4A  ", short_desc: "Exit Sensor Blocked.", caution_flag: 1, alert_flag: 0},
  {status: "4C  ", short_desc: "Bills.", caution_flag: 1, alert_flag: 0},
  {status: "4D  ", short_desc: "Exit Sensor Blocked.", caution_flag: 1, alert_flag: 0},
  {status: "6   ", short_desc: "Magnets set incorrectly.", caution_flag: 1, alert_flag: 0},
  {status: "9001", short_desc: "Format error.", caution_flag: 0, alert_flag: 0},
  {status: "9002", short_desc: "Reject cassette problem.", caution_flag: 1, alert_flag: 0},
  {status: "9003", short_desc: "Delivery error.", caution_flag: 1, alert_flag: 0},
  {status: "9004", short_desc: "Too many notes requested.", caution_flag: 1, alert_flag: 0},
  {status: "9005", short_desc: "Too many notes on conveyor.", caution_flag: 1, alert_flag: 0},
  {status: "9006", short_desc: "Illegal cassette number.", caution_flag: 1, alert_flag: 0},
  {status: "9007", short_desc: "Main Motor failure.", caution_flag: 1, alert_flag: 0},
  {status: "9008", short_desc: "High pressure.", caution_flag: 1, alert_flag: 0},
  {status: "9009", short_desc: "Communication problem.", caution_flag: 0, alert_flag: 0},
  {status: "9010", short_desc: "BD not set (Lifts are down).", caution_flag: 1, alert_flag: 0},
  {status: "9011", short_desc: "Cassette 5 out of notes.", caution_flag: 1, alert_flag: 0},
  {status: "9012", short_desc: "Cassette 6 out of notes.", caution_flag: 1, alert_flag: 0},
  {status: "9013", short_desc: "Cassette 5 low on notes.", caution_flag: 1, alert_flag: 0},
  {status: "9014", short_desc: "Cassette 6 low on notes.", caution_flag: 1, alert_flag: 0},
  {status: "9015", short_desc: "Gain out limit.", caution_flag: 1, alert_flag: 0},
  {status: "9016", short_desc: "Feed sensor fail.", caution_flag: 1, alert_flag: 0},
  {status: "9017", short_desc: "Internal error.", caution_flag: 1, alert_flag: 0},
  {status: "9018", short_desc: "Reject cassette overfilled.", caution_flag: 1, alert_flag: 0},
  {status: "9019", short_desc: "Timeout while waiting for device to respond.", caution_flag: 1, alert_flag: 0},
  {status: "9020", short_desc: "Notes detected in throat (bill jam)", caution_flag: 1, alert_flag: 0}
])

TranFieldDesc.create!([
  {field_name: "amt_auth", short_desc: "Amt Auth"},
  {field_name: "amt_req", short_desc: "Amt Req"},
  {field_name: "bank_id_nbr", short_desc: "Bank ID"},
  {field_name: "card_nbr", short_desc: "Card #"},
  {field_name: "cassette_1_disp", short_desc: "Cass 1"},
  {field_name: "cassette_2_disp", short_desc: "Cass 2"},
  {field_name: "cassette_3_disp", short_desc: "Cass 3"},
  {field_name: "cassette_4_disp", short_desc: "Cass 4"},
  {field_name: "cassette_5_disp", short_desc: "Cass 5"},
  {field_name: "cassette_6_disp", short_desc: "Cass 6"},
  {field_name: "coin_1_disp", short_desc: "Coin 1"},
  {field_name: "coin_2_disp", short_desc: "Coin 2"},
  {field_name: "coin_3_disp", short_desc: "Coin 3"},
  {field_name: "coin_4_disp", short_desc: "Coin 4"},
  {field_name: "coin_5_disp", short_desc: "Coin 5"},
  {field_name: "coin_6_disp", short_desc: "Coin 6"},
  {field_name: "coin_disp", short_desc: "Coin tot"},
  {field_name: "date_time", short_desc: "Date"},
  {field_name: "dev_id", short_desc: "Dev ID"},
  {field_name: "error_code", short_desc: "Err Code"},
  {field_name: "event_id", short_desc: "Event ID"},
  {field_name: "receipt_nbr", short_desc: "Receipt"},
  {field_name: "track2", short_desc: "Track 2"},
  {field_name: "tran_code", short_desc: "Tran Cd"},
  {field_name: "tran_status", short_desc: "Status"}
])

TranStatusDesc.create!([
  {tran_status: 1, short_desc: "Handshake", long_desc: "This indicates a handshake between EZCash and another entity", icon: nil},
  {tran_status: 2, short_desc: "Handshake", long_desc: "This indicates a completed handshake between EZCash and another entity.", icon: nil},
  {tran_status: 3, short_desc: "Key Request", long_desc: "This indicates a request for a new key for a device", icon: nil},
  {tran_status: 4, short_desc: "Key Request", long_desc: "This indicates a completed key request", icon: nil},
  {tran_status: 9, short_desc: "New request", long_desc: "This status indicates a transaction is being processed. If it stays a type 9, there was a problem during processing.", icon: "C:\\CM Icons\\onhold.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "},
  {tran_status: 10, short_desc: "New request", long_desc: "This status indicates a transaction is being processed. If it stays a type 10, there was a problem during processing.", icon: "C:\\CM Icons\\onhold.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "},
  {tran_status: 11, short_desc: "Authorized", long_desc: "This indicates an authorized transaction that has not yet gotten a response from the ATM or dispenser to indicate success or failure of the dispense.", icon: "C:\\CM Icons\\clear.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "},
  {tran_status: 12, short_desc: "Completed", long_desc: "This is an authorized transaction that the dispenser has indicated was a successful dispense.", icon: "C:\\CM Icons\\clear.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "},
  {tran_status: 13, short_desc: "Void", long_desc: "The transaction failed. Some or all of the amount requested could not be dispensed. See the error_code for more detail.", icon: "C:\\CM Icons\\not_clear.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "},
  {tran_status: 14, short_desc: "Hold", long_desc: "The transaction is on hold", icon: "C:\\CM Icons\\onhold.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "},
  {tran_status: 15, short_desc: "Reversed", long_desc: "The transaction was authorized, but the dispenser or ATM could not dispense some or all of the cash. See the error_code for more detail.", icon: nil},
  {tran_status: 16, short_desc: "Denied", long_desc: "The transaction was denied.", icon: "C:\\CM Icons\\denied.png                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "}
])

TudUserAuth.create!([
  {UserName: "Adept Data Solutions", UserHash: "fdc90d44dcca23c81e4c1c06f158d733"},
  {UserName: "Gerdau", UserHash: "d627679f1fdac445ffb4c5a62cf2c882"},
  {UserName: "ScrapDragon", UserHash: "688ede669afa36d251dcb88e89eadef5"},
  {UserName: "Tenaris", UserHash: "9cb9f6c01988bd18c8be5b3f599ca6aa"}
])

User.create!([
  {user_name: "ez", pwd_hash: "8a8bb7cd343aa2ad99b7d762030857a2", user_role_index: 5, pwd_needs_change: 0, pwd_last_changed: "1899-12-30 00:00:00", win_auth: 0, dev_group: nil, dev_site: nil, disable_add: 0},
  {user_name: "manager", pwd_hash: "df7efb50f6da87818a11f5ea5f6f7f09", user_role_index: 3, pwd_needs_change: 0, pwd_last_changed: nil, win_auth: nil, dev_group: nil, dev_site: nil, disable_add: 0},
  {user_name: "replenisher", pwd_hash: "2541c4cb94e881e0a4f9d28efe0cd0cf", user_role_index: 4, pwd_needs_change: 0, pwd_last_changed: nil, win_auth: nil, dev_group: nil, dev_site: nil, disable_add: 0},
  {user_name: "superadmin", pwd_hash: "b6c1c42866f3f78328d2915fc575b77d", user_role_index: 5, pwd_needs_change: 0, pwd_last_changed: nil, win_auth: nil, dev_group: nil, dev_site: nil, disable_add: 0}
])

EzPermissionDesc.create!([
  {PermissionID: 0, Description: "View Monitor"},
  {PermissionID: 1, Description: "Control Devices"},
  {PermissionID: 2, Description: "View Profiles"},
  {PermissionID: 3, Description: "Edit Profiles"},
  {PermissionID: 4, Description: "View Devices"},
  {PermissionID: 5, Description: "Edit Devices"},
  {PermissionID: 6, Description: "Edit Denoms"},
  {PermissionID: 7, Description: "Replenish Cash"},
  {PermissionID: 8, Description: "Replenish Coin"},
  {PermissionID: 9, Description: "Read Barcodes"},
  {PermissionID: 10, Description: "Void Barcodes"},
  {PermissionID: 11, Description: "Edit Roles"}
])

OpCodeMap.create!([
  {KeySeq: "A A  ? ?", TranCode: "WDLT", CassetteID: nil, SwxPriTran: "WDL", SwxSecTran: "TFR", SwxSecRev: "REVT"},
  {KeySeq: "A F", TranCode: "CUT", CassetteID: nil, SwxPriTran: "CUT", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A G", TranCode: "PRNT", CassetteID: nil, SwxPriTran: "PRNT", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HAB", TranCode: "CSHR", CassetteID: 3, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HAC", TranCode: "ADD", CassetteID: 3, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HBB", TranCode: "CSHR", CassetteID: 4, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HBC", TranCode: "ADD", CassetteID: 4, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HHB", TranCode: "CSHR", CassetteID: 2, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HHC", TranCode: "ADD", CassetteID: 2, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HIB", TranCode: "CSHR", CassetteID: 1, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A HIC", TranCode: "ADD", CassetteID: 1, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "A I", TranCode: "TOTS", CassetteID: nil, SwxPriTran: "TOTS", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "AA", TranCode: "INQ", CassetteID: nil, SwxPriTran: "INQ", SwxSecTran: "NORM", SwxSecRev: nil},
  {KeySeq: "AB", TranCode: "WDLP", CassetteID: nil, SwxPriTran: "ALL", SwxSecTran: "TFR", SwxSecRev: "REVT"},
  {KeySeq: "ABBBBB", TranCode: "PINQ", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "INQ", SwxSecRev: nil},
  {KeySeq: "AC", TranCode: "WDLT", CassetteID: nil, SwxPriTran: "WDL", SwxSecTran: "TFR", SwxSecRev: "REVT"},
  {KeySeq: "AD", TranCode: "PINC", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "CHNG", SwxSecRev: nil},
  {KeySeq: "ADD", TranCode: "PINN", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "NEW", SwxSecRev: nil},
  {KeySeq: "BA A ? ?", TranCode: "CHK", CassetteID: nil, SwxPriTran: "CHK", SwxSecTran: "ACK", SwxSecRev: nil},
  {KeySeq: "BB A ? ?", TranCode: "DEPC", CassetteID: nil, SwxPriTran: "CASH", SwxSecTran: "TFR", SwxSecRev: nil},
  {KeySeq: "C A  A A", TranCode: "TOTS", CassetteID: nil, SwxPriTran: "TOTS", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "C?A", TranCode: "PRNT", CassetteID: nil, SwxPriTran: "PRNT", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "CAA ? A", TranCode: "PINQ", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "INQ", SwxSecRev: nil},
  {KeySeq: "CCA  ? ?", TranCode: "PINQ", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "INQ", SwxSecRev: nil},
  {KeySeq: "GC??????", TranCode: "BILL", CassetteID: nil, SwxPriTran: "BILL", SwxSecTran: "LIST", SwxSecRev: nil},
  {KeySeq: "GK", TranCode: "KEYB", CassetteID: nil, SwxPriTran: "KEY", SwxSecTran: "GENB", SwxSecRev: nil},
  {KeySeq: "IA   A ?", TranCode: "PINC", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "CHNG", SwxSecRev: nil},
  {KeySeq: "IC", TranCode: "CRDI", CassetteID: nil, SwxPriTran: "CARD", SwxSecTran: "UPD", SwxSecRev: nil},
  {KeySeq: "ID   ? ?", TranCode: "PINC", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "CHNG", SwxSecRev: nil},
  {KeySeq: "IP", TranCode: "PINN", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "NEW", SwxSecRev: nil},
  {KeySeq: "JA", TranCode: "CUT", CassetteID: nil, SwxPriTran: "CUT", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JB", TranCode: "CUT", CassetteID: nil, SwxPriTran: "CUT", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JC", TranCode: "TOTS", CassetteID: nil, SwxPriTran: "TOTS", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JD", TranCode: "CUT", CassetteID: nil, SwxPriTran: "CUT", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JE", TranCode: "CUTD", CassetteID: nil, SwxPriTran: "CUTD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JF", TranCode: "PRNT", CassetteID: nil, SwxPriTran: "PRNT", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JG??A", TranCode: "CSHR", CassetteID: 1, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JG??B", TranCode: "CSHR", CassetteID: 2, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JG??C", TranCode: "CSHR", CassetteID: 3, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JG??D", TranCode: "CSHR", CassetteID: 4, SwxPriTran: "CSHR", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JH??A", TranCode: "ADD", CassetteID: 1, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JH??B", TranCode: "ADD", CassetteID: 2, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JH??C", TranCode: "ADD", CassetteID: 3, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "JH??D", TranCode: "ADD", CassetteID: 4, SwxPriTran: "ADD", SwxSecTran: "SUPV", SwxSecRev: nil},
  {KeySeq: "KEYA", TranCode: "KEYA", CassetteID: nil, SwxPriTran: "KEY", SwxSecTran: "GENA", SwxSecRev: nil},
  {KeySeq: "KEYB", TranCode: "KEYB", CassetteID: nil, SwxPriTran: "KEY", SwxSecTran: "GENB", SwxSecRev: nil},
  {KeySeq: "PP", TranCode: "DEPT", CassetteID: nil, SwxPriTran: "DEP", SwxSecTran: "TFR", SwxSecRev: "REVT"},
  {KeySeq: "VP", TranCode: "PINQ", CassetteID: nil, SwxPriTran: "PIN", SwxSecTran: "INQ", SwxSecRev: nil}
])
